# SPRING PROFILES
spring:
  ## DB
  datasource:
    url: jdbc:mysql://${server.mysql.hostname}:${server.mysql.port}/${server.mysql.database.access-center.name}?useUnicode=true&characterEncoding=GBK&serverTimezone=UTC&useSSL=false
    username: ${server.mysql.database.access-center.username}
    password: ${server.mysql.database.access-center.password}
    driver-class-name: ${datasource.driver-class-name}
  ## SPRING DATA JPA
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    properties:
      jadira.usertype.autoRegisterUserTypes: true
      hibernate.enable_lazy_load_no_trans: true
    hibernate:
      ddl-auto: validate
    generate-ddl: true
  #redis
  redis:
    #Redis数据库索引？？
    host: ${server.redis.host}
    port: ${server.redis.port}
    password: ${server.redis.password}
    jedis:
      pool:
        #连接池的最大连接数,使用负值表示没有限制
        max-active: 100
        #连接池的最大阻塞等待时间，使用负值表示没有限制
        max-wait: 1
        #连接池中的最大空闲连接
        max-idle: 10
        #连接池中的最小空闲连接
        min-idle: 0
    #连接超时时间（毫秒）
    timeout: 1000

  flyway:
    enabled: true
    locations: classpath:db/migration
  main:
    allow-bean-definition-overriding: true

  rabbitmq:
    host: ${server.rabbitmq.addresses}
    port: ${server.rabbitmq.port}
    username: ${server.rabbitmq.username}
    password: ${server.rabbitmq.password}


custom:
  amqp:
    maxPoolSize: 100
    corePoolSize: 10
    keepAliveSeconds: 30000
    queueCapacity: 5


server:
  port: 8083



bloom:
  filter:
    expectedInsertions: 1000
    fpp: 0.001F



scheduler:
  start:
    time:
      alarmJob: 0 0 11 * * ? *
      #      queryCapacityJob: 0 0 3 * * ? *
      timeZone: Asia/Shanghai


